org: marcellogc
app: helpinho
service: helpinho

plugins:
  - serverless-offline
  - serverless-plugin-monorepo
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    host: 0.0.0.0
    noPrependStageInUrl: true
  stage: "${opt:stage, self:provider.stage}"
  usersTable: "${self:service}-users-${self:custom.stage}"
  helpinhosTable: "${self:service}-helpinhos-${self:custom.stage}"
  helpsTable: "${self:service}-helps-${self:custom.stage}"
  uploadBucket: "${self:service}-bucket-${self:custom.stage}"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:GetObjectAcl
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/users
        - arn:aws:dynamodb:${self:provider.region}:*:table/users/index/*
        - arn:aws:dynamodb:${self:provider.region}:*:table/helpinhos
        - arn:aws:dynamodb:${self:provider.region}:*:table/helpinhos/index/*
        - arn:aws:dynamodb:${self:provider.region}:*:table/helps
        - arn:aws:dynamodb:${self:provider.region}:*:table/helps/index/*
        - arn:aws:s3:::helpinho-uploads-m/*
  environment: ${file(configs.js)}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: any
          path: /{any+}
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    helpinhosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.helpinhosTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    helpsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.helpsTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: helpinhoId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: HelpinhoIdIndex
            KeySchema:
              - AttributeName: helpinhoId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    uploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.uploadBucket}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - HEAD
                - PUT
              AllowedOrigins:
                - "*"
