version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - type: bind
        source: ${SSH_AUTH_SOCK}
        target: /ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent

    command: sleep infinity

    ports:
      - 3000:3000
      - 3002:3002

    extra_hosts:
      - "host.docker.internal:host-gateway"
